### ISSUE TITLE
Silkie doesn't generate correct output when specifying certain path

### ISSUE THREAD

**Issue by TueNguyen2911** [oliver-pham/silkie#4]
When specifying input path as (`current directory` + `folder` or `text file`), for example: `python silkie.py -i ./haha.txt`, the program generates nameless .html file, though its `tittle` and `h1` are correct. 

### Error (a single input file) 
![image](https://user-images.githubusercontent.com/58532267/133550948-b387b854-5013-4aa4-85b8-4b77e8be7b21.png)

When a `folder` with more than 1 text file is specified, the program generates only 1 html file (the last text file in the     ####folder)

## Error (an input folder) 
![image](https://user-images.githubusercontent.com/58532267/133551129-7311ff87-7dd9-43f6-9dfe-2e3a3f81e124.png)

**Comment by ycechungAI** [comment]
i have this issue on windows 10 will push code fix for it
