### ISSUE TITLE
Make newline regex cross-platform aware

### ISSUE THREAD

**Issue by humphd** [oliver-pham/silkie#9]
I would improve the regex dealing with newlines.  It currently assumes `\n` but on Windows you will encounter `\r\n` as well.  I usually use `\r?\n` to indicate the line feed is optional.

For example, https://github.com/oliver-pham/silkie/blob/main/silkie.py#L64.

**Comment by oliver-pham** [comment]
I think my collaborator and I have discussed this issue in #6 . I think we can safely exclude it since Python [translates all the newline characters to `\n`](https://docs.python.org/3/library/functions.html#open) in universal newline character mode.
